table DimProject
	lineageTag: f6807f48-94ab-4299-8e16-89096e39029f

	column ProjectKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3df950c2-8174-48c0-bc35-2348ec2f8284
		summarizeBy: none
		sourceColumn: ProjectKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProjectID
		dataType: string
		lineageTag: d209c505-9928-46fc-a966-c44a3a410d82
		summarizeBy: none
		sourceColumn: ProjectID

		annotation SummarizationSetBy = Automatic

	column ProjectName
		dataType: string
		lineageTag: 2fd75a77-2577-46b4-9ce5-2994549b7493
		summarizeBy: none
		sourceColumn: ProjectName

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5af08b0-89b3-41ce-bbf0-bdcc7c0f2746
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: e50ff93d-436f-439c-888c-b3b56d5bf699
			defaultHierarchy: LocalDateTable_4fb18273-ba6a-4eee-9472-9587e2bade35.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BaselineCompletionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa2a3f74-e353-48eb-8bad-34148d58a96c
		summarizeBy: none
		sourceColumn: BaselineCompletionDate

		variation Variation
			isDefault
			relationship: a41cec0e-fdda-4ea4-b88a-3dadfc406b78
			defaultHierarchy: LocalDateTable_be8fa65b-141c-4e9b-8557-ebe2d0b1be66.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PlannedDurationMonths
		dataType: int64
		formatString: 0
		lineageTag: 5f1afc55-0273-4879-a288-28ba8067e00e
		summarizeBy: sum
		sourceColumn: PlannedDurationMonths

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: e289e45e-d951-4d81-9b97-331362079ca1
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Complexity
		dataType: string
		lineageTag: ba9ab986-690c-4778-9a33-3534cf133832
		summarizeBy: none
		sourceColumn: Complexity

		annotation SummarizationSetBy = Automatic

	column StrategicAlignmentScore
		dataType: int64
		formatString: 0
		lineageTag: 5ffa87c9-31d2-4cbf-b9ea-801ba130f590
		summarizeBy: sum
		sourceColumn: StrategicAlignmentScore

		annotation SummarizationSetBy = Automatic

	column ScenarioArchetype
		dataType: string
		isHidden
		lineageTag: 7a20bd72-5166-469b-a8e3-019809b5b647
		summarizeBy: none
		sourceColumn: ScenarioArchetype

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Final Status' = CALCULATE ( SELECTEDVALUE ( FactProjectMonthly[ProjectStatus] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: string
		lineageTag: 88114f1e-4792-41de-8aee-74795dd9c800
		summarizeBy: none

	column 'Final RAG' = CALCULATE ( SELECTEDVALUE ( FactProjectMonthly[RAGStatus] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: string
		lineageTag: cd140fa8-814f-4c2c-8450-c8f2d9fa8c6d
		summarizeBy: none

	column 'Final Health' = CALCULATE ( MAX ( FactProjectMonthly[PortfolioHealthScore] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		formatString: 0.0
		lineageTag: 711c7454-bdb0-4dc4-96d9-165ba10714cd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final SPI' = CALCULATE ( MAX ( FactProjectMonthly[SchedulePerformanceIndex] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		formatString: 0.000
		lineageTag: 5ac0da63-1dd3-4f15-84a9-c84086433fa5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final CPI' = CALCULATE ( MAX ( FactProjectMonthly[CostPerformanceIndex] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		formatString: 0.000
		lineageTag: 52220fcb-3901-4c0b-9801-f7d5ff136b99
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final Delay Days' = CALCULATE ( MAX ( FactProjectMonthly[ForecastDelayDays] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: int64
		lineageTag: 19571502-0132-478b-9f37-0a290beb4104
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final Risk Exposure' = CALCULATE ( MAX ( FactProjectMonthly[RiskExposureScore] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		lineageTag: d480c9ef-d6bd-4062-b62b-6d51b9b06cad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final Overdue Mitigations' = CALCULATE ( MAX ( FactProjectMonthly[OverdueMitigationActions] ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: int64
		lineageTag: 0fedb9bd-7a84-4753-9c65-df3830ba4b4d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final BCR' = CALCULATE ( DIVIDE ( MAX ( FactProjectMonthly[ForecastBenefitEUR] ), MAX ( FactProjectMonthly[ForecastTotalCostEUR] ) ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		formatString: 0.00
		lineageTag: c1f00843-171d-4649-80dd-20dffa5d75a0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final Benefit Outlook %' = CALCULATE ( DIVIDE ( MAX ( FactProjectMonthly[ForecastBenefitEUR] ), MAX ( FactProjectMonthly[PlannedBenefitEUR] ) ) - 1, FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		formatString: 0.0%
		lineageTag: 3a2c0e75-e331-4f3f-88be-a96b8d9e8d74
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Final Capacity Gap %' = CALCULATE ( DIVIDE ( MAX ( FactProjectMonthly[ResourceCapacityGapHours] ), MAX ( FactProjectMonthly[PlannedResourceHours] ) ), FactProjectMonthly[Is Final Snapshot] = 1 )
		dataType: double
		lineageTag: f9dc17ce-0189-40f2-ba0a-57c99e22730f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Recommended Action' =
			SWITCH (
			    DimProject[Action Sort],
			    1, "Terminate",
			    2, "Pause",
			    3, "Recover (high priority)",
			    4, "Recover (monitor)",
			    5, "Accelerate",
			    6, "Maintain",
			    "Closed"
			)
		dataType: string
		lineageTag: c2b0aa0f-a818-4b8b-afec-860c3884f827
		summarizeBy: none
		sortByColumn: 'Action Sort'

	column 'Primary Issue' =
			IF (
			    NOT ( DimProject[Recommended Action] IN { "Recover (high priority)", "Recover (monitor)", "Pause", "Terminate" } ), BLANK (),
			    SWITCH (
			        TRUE (),
			        DimProject[Final Capacity Gap %] < -0.15,                                              "Resource shortfall",
			        DimProject[Final Benefit Outlook %] < -0.15,                                           "Benefit shortfall",
			        DimProject[Final Risk Exposure] >= 80 || DimProject[Final Overdue Mitigations] >= 2,   "Risk exposure",
			        "Schedule / cost slippage"
			    )
			)
		dataType: string
		lineageTag: f46ed66b-5a92-405c-afe5-9588c915459e
		summarizeBy: none

	column 'Action Sort' =
			VAR InFlight = DimProject[Final Status] IN { "Active", "Paused" }
			VAR H  = DimProject[Final Health]
			VAR B  = DimProject[Final BCR]
			VAR BO = DimProject[Final Benefit Outlook %]
			VAR CG = DimProject[Final Capacity Gap %]
			RETURN
			    SWITCH (
			        TRUE (),
			        NOT InFlight,                                7,
			        H < 65 && B < 1,                             1,
			        H < 65,                                      2,
			        H >= 90 && BO >= 0 && CG >= 0 && B >= 1.5,   5,
			        ( H < 90 || BO < -0.15 ) && ( H < 80 || BO < -0.15 || DimProject[Priority] = "Critical" ), 3,
			        H < 90 || BO < -0.15,                        4,
			        6
			    )
		dataType: int64
		lineageTag: 05d6b7c8-be0c-4635-a21b-c01b0f58340c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DimProject = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\ENVY\Downloads\PMO-Portfolio_C41\PMO Portfolio_From Strategy to Success_C41.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimProject", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProjectKey", Int64.Type}, {"ProjectID", type text}, {"ProjectName", type text}, {"StartDate", type date}, {"BaselineCompletionDate", type date}, {"PlannedDurationMonths", Int64.Type}, {"Priority", type text}, {"Complexity", type text}, {"StrategicAlignmentScore", Int64.Type}, {"ScenarioArchetype", type text}}, "en-US")
				in
				  #"Changed column type"

