table DimBusinessUnit
	lineageTag: 323d1703-878c-47dc-9d53-bbbaa972d9c1

	column BusinessUnitKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e30c0016-b30a-4c75-a0df-aa6712503819
		summarizeBy: none
		sourceColumn: BusinessUnitKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BusinessUnitName
		dataType: string
		lineageTag: b9a99f39-4259-4667-82c5-2831a99d7f0d
		summarizeBy: none
		sourceColumn: BusinessUnitName

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 24156004-04ff-4e54-9ec6-351f6267bf19
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column PrimaryValueDriver
		dataType: string
		lineageTag: 4eeb1a6f-3082-41b3-88d8-1cc8a0394f47
		summarizeBy: none
		sourceColumn: PrimaryValueDriver

		annotation SummarizationSetBy = Automatic

	partition DimBusinessUnit = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\ENVY\Downloads\PMO-Portfolio_C41\PMO Portfolio_From Strategy to Success_C41.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimBusinessUnit", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"BusinessUnitKey", Int64.Type}, {"BusinessUnitName", type text}, {"Division", type text}, {"PrimaryValueDriver", type text}}, "en-US")
				in
				  #"Changed column type"

