table DimDeliveryModel
	lineageTag: 2ff03d88-6aa7-41f1-9323-125a91eefe32

	column DeliveryModelKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3476831e-f374-443c-a41b-5e2b8232f707
		summarizeBy: none
		sourceColumn: DeliveryModelKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DeliveryModel
		dataType: string
		lineageTag: d94f3aa3-9981-40b1-aee8-f2fd030dc19d
		summarizeBy: none
		sourceColumn: DeliveryModel

		annotation SummarizationSetBy = Automatic

	column GovernanceApproach
		dataType: string
		lineageTag: 3205ed45-9430-4218-8668-b18d5ea89789
		summarizeBy: none
		sourceColumn: GovernanceApproach

		annotation SummarizationSetBy = Automatic

	partition DimDeliveryModel = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\ENVY\Downloads\PMO-Portfolio_C41\PMO Portfolio_From Strategy to Success_C41.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimDeliveryModel", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"DeliveryModelKey", Int64.Type}, {"DeliveryModel", type text}, {"GovernanceApproach", type text}}, "en-US")
				in
				  #"Changed column type"

