table DimEmployee
	lineageTag: 982a1138-f125-46db-9130-929a21b4b878

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 45ecca3a-2ecd-4cac-a988-941078dfeba8
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: a0f37c86-6dd7-4459-9670-5d749ce6e03b
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column PortfolioRole
		dataType: string
		lineageTag: 9eda4205-c73e-42d7-afc3-21beebc349b4
		summarizeBy: none
		sourceColumn: PortfolioRole

		annotation SummarizationSetBy = Automatic

	column Seniority
		dataType: string
		lineageTag: 2f928239-4b1a-48f6-a247-3548c186f998
		summarizeBy: none
		sourceColumn: Seniority

		annotation SummarizationSetBy = Automatic

	column HomeBusinessUnitKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 842e7058-de6c-41d2-9452-86ac0dd99e22
		summarizeBy: none
		sourceColumn: HomeBusinessUnitKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimEmployee = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\ENVY\Downloads\PMO-Portfolio_C41\PMO Portfolio_From Strategy to Success_C41.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimEmployee", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"EmployeeKey", Int64.Type}, {"EmployeeName", type text}, {"PortfolioRole", type text}, {"Seniority", type text}, {"HomeBusinessUnitKey", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

