table DimLocation
	lineageTag: b6fa76a4-c940-401e-9a74-42924bdbfa4d

	column LocationKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fdc4d20f-90c1-4bee-a5bf-0a50d1711568
		summarizeBy: none
		sourceColumn: LocationKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: cb5c5485-343c-4f3b-9a5f-17d39fa4ba14
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 156b4d33-a797-482c-93e3-0973c6e465e7
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1a168823-aa1f-4bd1-a9d0-11ff8c0bf3a9
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 905db148-2126-435a-a4ae-140e6124a56e
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 4a4a243b-c648-4687-9db1-e5bd2720d837
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimLocation = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\ENVY\Downloads\PMO-Portfolio_C41\PMO Portfolio_From Strategy to Success_C41.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimLocation", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"LocationKey", Int64.Type}, {"City", type text}, {"Country", type text}, {"Region", type text}, {"Latitude", type number}, {"Longitude", type number}}, "en-US")
				in
				  #"Changed column type"

