table DimProgramme
	lineageTag: 7b47b740-6e01-4770-85c0-83d3c1bb10e2

	column ProgrammeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b90b7049-758e-4330-956f-1d3d63457662
		summarizeBy: none
		sourceColumn: ProgrammeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProgrammeName
		dataType: string
		lineageTag: c1b20b2a-2adb-4aee-8d0e-139e68b9f2e2
		summarizeBy: none
		sourceColumn: ProgrammeName

		annotation SummarizationSetBy = Automatic

	column PortfolioCategory
		dataType: string
		lineageTag: fc42b550-b3cf-4c71-9577-95c9152de957
		summarizeBy: none
		sourceColumn: PortfolioCategory

		annotation SummarizationSetBy = Automatic

	column LeadBusinessUnitKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b123c566-62f0-4914-aee3-a8206ef3246e
		summarizeBy: none
		sourceColumn: LeadBusinessUnitKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimProgramme = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\ENVY\Downloads\PMO-Portfolio_C41\PMO Portfolio_From Strategy to Success_C41.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimProgramme", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProgrammeKey", Int64.Type}, {"ProgrammeName", type text}, {"PortfolioCategory", type text}, {"LeadBusinessUnitKey", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

